"""FIXED: added genres column back to  Artist Model as enum type

Revision ID: 3499df035ed1
Revises: 98e4ea8dcfd9
Create Date: 2022-06-02 20:48:51.919614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3499df035ed1'
down_revision = '98e4ea8dcfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
